# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('access_point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='IPC Camera', max_length=100, null=True)),
                ('serial', models.CharField(max_length=30, unique=True)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=False, verbose_name='Online')),
                ('status_detail', models.PositiveSmallIntegerField(choices=[(0, 'Not used'), (1, 'Used'), (2, 'Deleted')], default=0, verbose_name='Status')),
                ('is_publish', models.BooleanField(default=False, verbose_name='publish')),
                ('is_wza', models.BooleanField(default=False, verbose_name='wza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=150, null=True)),
                ('is_wifi', models.BooleanField(default=False, verbose_name='Wifi')),
                ('firmware', models.CharField(max_length=150)),
                ('access_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_access_point', to='access_point.AccessPoint')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_brand', to='brand.Brand')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_device_type', to='brand.DeviceType')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
            },
        ),
    ]
