# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 05:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('access_point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='IPC Camera', max_length=100, null=True)),
                ('serial', models.CharField(max_length=30, unique=True)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(choices=[(-1, 'Unknown'), (0, 'Online'), (1, 'Offline')], default=-1, verbose_name='Status')),
                ('status_detail', models.PositiveSmallIntegerField(choices=[(0, 'Not used'), (1, 'Used'), (2, 'Deleted')], default=0, verbose_name='Detail')),
                ('is_publish', models.BooleanField(default=False, verbose_name='publish')),
                ('is_wza', models.BooleanField(default=False, verbose_name='wza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=150, null=True)),
                ('is_wifi', models.BooleanField(default=False, verbose_name='Wifi')),
                ('firmware', models.CharField(max_length=150)),
                ('access_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_access_point', to='access_point.AccessPoint')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_brand', to='brand.Brand')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_device_type', to='brand.DeviceType')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
            },
        ),
        migrations.CreateModel(
            name='CameraTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('topics', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('ca_path', models.FileField(blank=True, null=True, upload_to='certificate/mqtt/', verbose_name='certificate')),
                ('ssl', models.BooleanField(default=False)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camera_topic', to='cameras.Camera')),
            ],
        ),
    ]
