# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ftp',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ftp',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='ftp',
            name='server',
        ),
        migrations.AlterField(
            model_name='server',
            name='domain_name',
            field=models.CharField(max_length=150, verbose_name='Host'),
        ),
        migrations.DeleteModel(
            name='FTP',
        ),
    ]
