# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 03:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('servers', '0002_auto_20190225_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField(default=21, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('ssl', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ftp_camera', to='cameras.Camera')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ftp_server', to='servers.Server')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ftp',
            unique_together=set([('host', 'port', 'username', 'camera', 'server')]),
        ),
    ]
