# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order number')),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
