# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 07:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/brand/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpeg', 'jpg', 'svg', 'icon'])])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('created_by', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('created_by', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Devices Type',
            },
        ),
        migrations.AlterUniqueTogether(
            name='devicetype',
            unique_together=set([('code_number',)]),
        ),
        migrations.AddField(
            model_name='brand',
            name='devices_type',
            field=models.ManyToManyField(blank=True, related_name='brand_devices_type', to='brand.DeviceType'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set([('name',)]),
        ),
    ]
