# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=150, null=True)),
                ('release_file', models.FileField(blank=True, null=True, upload_to='firmware/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=150, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmware_brand', to='brand.Brand')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmware_type', to='brand.DeviceType')),
            ],
        ),
    ]
