# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('old_password', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'User'), (1, 'Admin'), (2, 'Modifier')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=150, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_camera', to='cameras.Camera')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('camera', 'username')]),
        ),
    ]
